config/routes.rb
# frozen_string_literal: true

#  BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
#  Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
#  This program is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free Software
#  Foundation; either version 3.0 of the License, or (at your option) any later
#  version.
#
#  BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License along
#  with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get '/health_check', to: 'health_check#all'
  get '/healthz', to: 'health_check#all'
  root to: 'health_check#all'

  mount ActionCable.server => "#{ENV['RELATIVE_URL_ROOT'] ? '/' + ENV['RELATIVE_URL_ROOT'] : ''}/rooms/cable"

  scope ENV['RELATIVE_URL_ROOT'] || '' do
    scope 'rooms' do
      get '/health_check', to: 'health_check#all'
      get '/healthz', to: 'health_check#all'

      # Handles meeting management.
      scope ':id/meeting' do
        post '/join', to: 'rooms#meeting_join', as: :meeting_join
        get '/join', to: 'rooms#meeting_join'
        post '/end', to: 'rooms#meeting_end', as: :meeting_end
        get '/close', to: 'rooms#meeting_close', as: :autoclose
      end

      # Handles recording management.
      scope ':id/recording/:record_id' do
        post '/publish', to: 'rooms#recording_publish', as: :recording_publish
        post '/unpublish', to: 'rooms#recording_unpublish', as: :recording_unpublish
        post '/protect', to: 'rooms#recording_protect', as: :recording_protect
        post '/unprotect', to: 'rooms#recording_unprotect', as: :recording_unprotect
        post '/update', to: 'rooms#recording_update', as: :recording_update
        post '/delete', to: 'rooms#recording_delete', as: :recording_delete
      end

      # Handles launches.
      get 'launch', to: 'rooms#launch', as: :room_launch

      # Handles sessions.
      get '/sessions/create'
      get '/sessions/failure'

      # Handles Omniauth authentication.
      get '/auth/:provider', to: 'sessions#new', as: :omniauth_authorize
      get '/auth/:provider/callback', to: 'sessions#create', as: :omniauth_callback
      get '/auth/failure', to: 'sessions#failure', as: :omniauth_failure

      # Handles errors.
      get '/errors/:code', to: 'errors#index', as: :errors
    end

    resources :rooms
  end
end

app/models/room.rb
# frozen_string_literal: true

#  BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
#  Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
#  This program is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free Software
#  Foundation; either version 3.0 of the License, or (at your option) any later
#  version.
#
#  BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License along
#  with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
class Room < ApplicationRecord
  before_save :default_values

  attr_accessor :can_grade

  def default_values
    self.handler ||= Digest::SHA1.hexdigest(SecureRandom.uuid)
    self.moderator = random_password(8) if moderator.blank?
    self.viewer = random_password(8, moderator) if viewer.blank?
  end

  def broadcast_room_start
    ActionCable.server.broadcast("wait_channel:room_#{id}", action: 'started')
  end

  private

  def random_password(length, reference = '')
    o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map(&:to_a).flatten
    password = ''
    loop do
      password = (0...length).map { o[rand(o.length)] }.join
      break unless password == reference
    end
    password
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

#  BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
#  Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
#  This program is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free Software
#  Foundation; either version 3.0 of the License, or (at your option) any later
#  version.
#
#  BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License along
#  with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

require 'bbb_app_rooms/user'

class RoomsController < ApplicationController
  # Include libraries.
  include BbbAppRooms
  # Include concerns.
  include BbbHelper
  include OmniauthHelper

  before_action :authenticate_user!, except: %i[meeting_close], raise: false
  before_action :set_launch, only: %i[launch]
  before_action :set_room, except: %i[launch]
  before_action :check_for_cancel, only: [:create, :update]
  before_action :allow_iframe_requests
  before_action :set_current_locale
  after_action :broadcast_meeting, only: [:meeting_end]

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    respond_to do |format|
      if @room
        begin
          @recordings = recordings
        rescue BigBlueButton::BigBlueButtonException => e
          logger.error(e.to_s)
          flash.now[:alert] = t('default.recording.server_down')
          @recordings = []
        end

        format.html { render(:show) }
        format.json { render(:show, status: :ok, location: @room) }
      else
        format.html { render(:error, status: @error[:status]) }
        format.json { render(json: { error: @error[:message] }, status: @error[:status]) }
      end
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to(@room, notice: t('default.room.created')) }
        format.json { render(:show, status: :created, location: @room) }
      else
        format.html { render(:new) }
        format.json { render(json: @error, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        Rails.cache.clear # Clear cache to reflect updated room
        format.html { redirect_to(room_path(@room, launch_nonce: params[:launch_nonce]), notice: t('default.room.updated')) }
        format.json { render(:show, status: :ok, location: @room) }
      else
        format.html { render(:edit) }
        format.json { render(json: @error, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to(rooms_url, notice: t('default.room.destroyed')) }
      format.json { head(:no_content) }
    end
  end

  # GET /launch
  # GET /launch.json?
  def launch
    redirect_to(room_path(@room.id, launch_nonce: params['launch_nonce']))
  end

  # POST /rooms/:id/meeting/join
  # POST /rooms/:id/meeting/join.json
  def meeting_join
    wait = wait_for_mod? && !meeting_running?
    @meeting = join_meeting_url

    if wait
      respond_to do |format|
        format.html
        format.json { render(json: { wait_for_mod: wait, meeting: @meeting }) }
      end
    else
      broadcast_meeting(action: 'join', delay: true)
      NotifyRoomWatcherJob.set(wait: 5.seconds).perform_later(@room, { action: 'started' }) if @room.wait_moderator
      redirect_to(@meeting)
    end
  end

  # GET /rooms/:id/meeting/end
  # GET /rooms/:id/meeting/end.json
  def meeting_end
    end_meeting
    redirect_to(room_path(@room.id, launch_nonce: params['launch_nonce'])) # fallback if actioncable doesn't work
  end

  def broadcast_meeting(action: 'none', delay: false)
    if delay
      NotifyMeetingWatcherJob.set(wait: 5.seconds).perform_later(@room, action: action)
    else
      NotifyMeetingWatcherJob.perform_now(@room, action: action)
    end
  end

  # GET /rooms/:id/meeting/close
  def meeting_close
    respond_to do |format|
      broadcast_meeting(action: 'someone left', delay: true)
      format.html { render(:autoclose) }
    end
  end

  # POST /rooms/:id/recording/:record_id/unpublish
  def recording_unpublish
    unpublish_recording(params[:record_id])
    redirect_to(room_path(params[:id], launch_nonce: params[:launch_nonce]))
  end

  # POST /rooms/:id/recording/:record_id/publish
  def recording_publish
    publish_recording(params[:record_id])
    redirect_to(room_path(params[:id], launch_nonce: params[:launch_nonce]))
  end

  # POST /rooms/:id/recording/:record_id/protect
  def recording_protect
    update_recording(params[:record_id], protect: true)
    redirect_to(room_path(params[:id], launch_nonce: params[:launch_nonce]))
  end

  # POST /rooms/:id/recording/:record_id/unprotect
  def recording_unprotect
    update_recording(params[:record_id], protect: false)
    redirect_to(room_path(params[:id], launch_nonce: params[:launch_nonce]))
  end

  # POST /rooms/:id/recording/:record_id/update
  def recording_update
    if params[:setting] == 'rename_recording'
      update_recording(params[:record_id], 'meta_name' => params[:record_name])
    elsif params[:setting] == 'describe_recording'
      update_recording(params[:record_id], 'meta_description' => params[:record_description])
    end
  end

  # POST /rooms/:id/recording/:record_id/delete
  def recording_delete
    delete_recording(params[:record_id])
    redirect_to(room_path(params[:id], launch_nonce: params[:launch_nonce]))
  end

  helper_method :recording_date, :recording_length, :meeting_running?, :bigbluebutton_moderator_roles,
                :bigbluebutton_recording_public_formats, :meeting_info, :bigbluebutton_recording_enabled, :server_running?

  private

  def set_error(error, status)
    @room = @user = nil
    @error = { key: t("error.room.#{error}.code"), message: t("error.room.#{error}.message"), suggestion: t("error.room.#{error}.suggestion"), status: status }
  end

  def authenticate_user!
    @launch_nonce = params['launch_nonce']
    return unless omniauth_provider?(:bbbltibroker)
    # Assume user authenticated if session [params[launch_nonce]] is set
    return if session[@launch_nonce]

    redirect_to(omniauth_authorize_path(:bbbltibroker, launch_nonce: params[:launch_nonce])) && return if params['action'] == 'launch'

    redirect_to(errors_path(401))
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find_by(id: params[:id])
    # Exit with error if room was not found
    set_error('notfound', :not_found) && return unless @room
    # Exit with error by re-setting the room to nil if the session for the room.handler is not set
    set_error('forbidden', :forbidden) && return unless session[@room.handler]

    # Continue through happy path
    @user = BbbAppRooms::User.new(session[@room.handler][:user_params])
  end

  def set_launch
    # Pull the Launch request_parameters.
    bbbltibroker_url = omniauth_bbbltibroker_url("/api/v1/sessions/#{@launch_nonce}")
    get_response = RestClient.get(bbbltibroker_url, 'Authorization' => "Bearer #{omniauth_client_token(omniauth_bbbltibroker_url)}")
    session_params = JSON.parse(get_response)
    if Rails.configuration.developer_mode_enabled
      logger.debug('>>>>>>>>> Session Params:')
      logger.debug(session_params.to_json)
    end

    # Exit with error if session_params is not valid.
    set_error('forbidden', :forbidden) && return unless session_params['valid']

    launch_params = session_params['message']

    # Exit with error if user is not authenticated.
    set_error('forbidden', :forbidden) && return unless launch_params['user_id'] == session[@launch_nonce]['uid']

    # Continue through happy path.
    @tenant = session_params['tenant']
    guid = launch_params['tool_consumer_instance_guid'] || launch_params['tool_consumer_instance_url']
    resource_handler = Digest::SHA1.hexdigest('rooms' + @tenant + guid + launch_params['resource_link_id'])
    @room = Room.find_or_create_by(handler: resource_handler, tenant: @tenant) do |room|
      room.update(launch_params_to_new_room_params(launch_params))
    end
    user_params = launch_params_to_new_user_params(launch_params)
    session[@room.handler] = { user_params: user_params }
  end

  def room_params
    params.require(:room).permit(:name, :description, :welcome, :moderator, :viewer, :recording, :wait_moderator, :all_moderators)
  end

  def new_room_params(name, description, recording = true, wait_moderator = false, all_moderators = false)
    params.permit.merge(
      name: name,
      description: description,
      welcome: '',
      recording: recording,
      wait_moderator: wait_moderator,
      all_moderators: all_moderators
    )
  end

  def launch_params_to_new_room_params(launch_params)
    name = launch_params['resource_link_title']
    description = launch_params['resource_link_description']
    record = launch_params['custom_params'].key?('custom_' + 'record') ? launch_params['custom_params']['custom_' + 'record'] : true
    wait_moderator = message_has_custom?(launch_params, 'wait_moderator')
    all_moderators = message_has_custom?(launch_params, 'all_moderators')
    new_room_params(name, description, record, wait_moderator, all_moderators)
  end

  def launch_params_to_new_user_params(launch_params)
    {
      uid: launch_params['user_id'],

app/helpers/rooms_helper.rb
# frozen_string_literal: true

#  BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
#  Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
#  This program is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free Software
#  Foundation; either version 3.0 of the License, or (at your option) any later
#  version.
#
#  BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License along
#  with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
module RoomsHelper
  def autoclose_url
    'javascript:window.close();'
  end

  def elapsed_time(start_time, curr_time)
    return 0 if start_time.nil?

    time = curr_time - start_time

    hrs = (time * 24).floor
    time -= hrs / 24.to_f

    mins = (time * 24 * 60).floor
    time -= mins / 1440.to_f

    secs = (time * 24 * 60 * 60).floor

    "#{add_zero_maybe(hrs)}:#{add_zero_maybe(mins)}:#{add_zero_maybe(secs)}"
  end

  def add_zero_maybe(num)
    num = '0' + num.to_s if num < 10

    num
  end
end

app/views/rooms/_error.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="alert alert-danger fade in">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <h4><strong><%= key %></strong>: <%= message %></h4>
  <p>
    <% if suggestion %>
    <%= suggestion %>
    <% end %>
  </p>
</div>

app/views/rooms/_form.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<%= form_with(model: room, local: true, class: "form fill", :url => room_path(@room, :launch_nonce => @launch_nonce) ) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group block input-group w-full rounded pt-8">
    <p>
      <%= form.label t('default.room.name') , style: "display: inline" %> 
      <span class="text-muted small text-red-500" style="display: inline"> *Required  </span>
    </p>
    <%= form.text_field :name, :required => true,  class: "form-control rounded-none rounded input mt-1 block w-full" %>
  </div> 

  <div class="field form-group input-group w-full pt-4">
    <%= form.label t('default.room.description') %>
    <%= form.text_area :description, size: "45x8", class: 'form-control input' %>
  </div>

  <div class="field form-group input-group w-full">
    <%= form.label t('default.room.welcome') %>
    <%= form.text_area :welcome, size: "45x4", class: 'form-control w-full input form-input' %>
  </div>

  <%= form.hidden_field :moderator, value: @room.moderator %>
  <%= form.hidden_field :viewer, value: @room.viewer %>

  <% if bigbluebutton_recording_enabled %>
    <div class="field form-group input-group pt-4">
      <%= form.check_box :recording %>&nbsp;
      <b><%= t('default.room.recording') %></b>&nbsp;
      <i class="glyphicon glyphicon-info-sign" data-toggle="tooltip" title="<%= t('default.room.tooltip.recording') %>"></i><br>
    </div>
  <% end %>

  <div class="field form-group input-group">
    <%= form.check_box :wait_moderator, id: 'wait_mod_checkbox' %>&nbsp;
    <b><%= t('default.room.waitmoderator') %></b>&nbsp;
    <i class="glyphicon glyphicon-info-sign" data-toggle="tooltip" title="<%= t('default.room.tooltip.waitmoderator') %>"></i><br>
  </div>

  <div class="field form-group input-group">
    <%= form.check_box :all_moderators, id: 'all_mod_checkbox' %>&nbsp;
    <b><%= t('default.room.allmoderators') %></b>&nbsp;
    <i class="glyphicon glyphicon-info-sign" data-toggle="tooltip" title="<%= t('default.room.tooltip.allmoderators') %>"></i><br>
  </div>

  <div class="actions pt-6">
    <div>
    <%= form.submit t('default.room.update'), class: "btn btn-primary " %>
    <%= form.button t('default.room.cancel'), class: "btn btn-default", name: "cancel" %>
  </div>
  </div>
<% end %>

app/views/rooms/autoclose.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<script type="text/javascript" language="JavaScript">window.close();</script>
<h1>Rooms#close</h1>
<%= t('default.meeting.close_manually') %>
<a href="javascript:;" onclick="window.close();" class="btn btn-default">Close</a>

app/views/rooms/edit.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>
<div class="container font-sans grid grid-flow-row auto-rows-max items-center justify-center pt-16 place-content-start px-4">
    <div class="text-6xl font-sans mb-4 font-medium"><%= t('default.room.edit') %></div>
    <div> <%= render 'form', room: @room %> </div>
</div>

app/views/rooms/error.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<h1><%= t('default.app.error') %></h1>

<% if @error %>
<%= render 'error', key: @error[:key], message: @error[:message], suggestion: @error[:suggestion] %>
<% end %>

app/views/rooms/meeting_join.html.erb
<head>

    <style>

        .header {
            padding: 60px;
            text-align: left;
            background: white;
            color: white;
            font-size: 30px;
        }

        .message-2{
            text-align: center; 
            position: relative;
            background-color: #F5F7FB;
            margin-top: 15px;
            padding-top: 8%;
            padding-bottom: 8%
        }
        
    </style>

</head>
<body data-meeting = <%=@meeting%>>
    <div class="container bg-white">
        <div class = "row">
            <div class ="flex items-start mt-20 mr-10 mb-10 ">
                <img style ="top:50%" alt="" src="https://raw.githubusercontent.com/bigbluebutton/greenlight/master/app/assets/images/logo_with_text.png">
            </div>
        </div>
        <div class="row">
            <div class = "bg-gray-200 grid justify-items-center grid-cols-1 gap-10 p-20 pt-40 pb-40" >
                <p class="font-sans text-5xl font-light pb-5"> <%= t('default.waiting_room.hang_tight') %> </p>
                <div class="loader pb-5"> </div>
                <p class="font-sans text-4xl font-light pt-5"> <%= t('default.waiting_room.redirect_msg') %> </p>
            </div>
        </div>
    </div>
</body>

app/views/rooms/new.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<h1><%= link_to t('default.admin.newroom'), new_room_path %></h1>

<%= render 'form', room: @room %>

<%= link_to t('default.admin.back'), rooms_path %>

app/views/rooms/show.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="container">

<%= render "shared/header" %>

<%= render "shared/body" %>

<%= render "shared/footer" %>

</div>