config/routes.rb
# frozen_string_literal: true

#  BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
#  Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
#  This program is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free Software
#  Foundation; either version 3.0 of the License, or (at your option) any later
#  version.
#
#  BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License along
#  with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get '/health_check', to: 'health_check#all'
  get '/healthz', to: 'health_check#all'
  root to: 'health_check#all'

  mount ActionCable.server => "#{ENV['RELATIVE_URL_ROOT'] ? '/' + ENV['RELATIVE_URL_ROOT'] : ''}/rooms/cable"

  scope ENV['RELATIVE_URL_ROOT'] || '' do
    scope 'rooms' do
      get '/health_check', to: 'health_check#all'
      get '/healthz', to: 'health_check#all'

      # Handles meeting management.
      scope ':id/meeting' do
        post '/join', to: 'rooms#meeting_join', as: :meeting_join
        get '/join', to: 'rooms#meeting_join'
        post '/end', to: 'rooms#meeting_end', as: :meeting_end
        get '/close', to: 'rooms#meeting_close', as: :autoclose
      end

      # Handles recording management.
      scope ':id/recording/:record_id' do
        post '/publish', to: 'rooms#recording_publish', as: :recording_publish
        post '/unpublish', to: 'rooms#recording_unpublish', as: :recording_unpublish
        post '/protect', to: 'rooms#recording_protect', as: :recording_protect
        post '/unprotect', to: 'rooms#recording_unprotect', as: :recording_unprotect
        post '/update', to: 'rooms#recording_update', as: :recording_update
        post '/delete', to: 'rooms#recording_delete', as: :recording_delete
      end

      # Handles launches.
      get 'launch', to: 'rooms#launch', as: :room_launch

      # Handles sessions.
      get '/sessions/create'
      get '/sessions/failure'

      # Handles Omniauth authentication.
      get '/auth/:provider', to: 'sessions#new', as: :omniauth_authorize
      get '/auth/:provider/callback', to: 'sessions#create', as: :omniauth_callback
      get '/auth/failure', to: 'sessions#failure', as: :omniauth_failure

      # Handles errors.
      get '/errors/:code', to: 'errors#index', as: :errors
    end

    resources :rooms
  end
end

app/views/shared/components/_recording_row.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>
<tr class="border-b text-left ">
  <td class="p-0">
    <div class="text-left font-sans px-8 py-4 ">
      <% can_edit = @user.admin? || @user.moderator?(bigbluebutton_moderator_roles) %>
      <% if can_edit %>
        <% hover = 'bg-gray-100' %>
        <% focus = 'bg-white' %>
      <% end %>
      <div id="recording-title" class="form-inline font-bold edit_hover_class" 
           data-recordid="<%= recording[:recordID] %>" 
           data-launch-nonce="<%= @launch_nonce %>" 
           data-can-edit="<%=can_edit%>">
          <% if recording[:metadata][:name] %>
              <text id='recording-title-text' class="text-wrap input recording-text"><%= recording[:metadata][:name] %></text>
          <% else %>
            <text id='recording-title-text' class="text-wrap input recording-text"><%= recording[:name] %></text>
          <% end %>
           <a><i id="edit-record-description" class="fa fa-edit align-top ml-2 hover: hover:text-blue-700" data-edit-recordid="<%= recording[:recordID] %>"></i></a>  

      </div>
      <div id="recording-description" class="form-inline edit_hover_class" 
           data-recordid="<%= recording[:recordID] %>" 
           data-launch-nonce="<%= @launch_nonce %>"
           data-can-edit="<%= can_edit %>">
        <text id='recording-description-text' class="text-wrap recording-text"><%= recording[:metadata][:description] %></text>
        <% if @user.admin? || @user.moderator?(bigbluebutton_moderator_roles) %>  
          <a><i id="edit-record-description" class="fa fa-edit align-top ml-2 bg-white hover:text-blue-700 hover:bg-white text-gray-700" data-edit-recordid="<%= recording[:recordID] %>"></i></a>  
        <% end %>
      </div>
    </div>
  </td>

  <td class="p-0 text-left font-sans px-8 py-4">
    <%= recording_date(recording[:startTime]) %>
  </td>

  <td class="p-0 text-left font-sans px-8 py-4">
    <%= recording_length(recording[:playbacks]) %>
  </td>

  <td class="p-0 text-left px-8 py-4" style='white-space: nowrap'>
    <div class="flex items-end ">
      <% if recording[:published] %>
        <% sorted_playbacks = recording[:playbacks].sort_by { |hsh| hsh[:type] }%>
        <% sorted_playbacks.each do |p| %>
          <% # Don't show playback if user isn't moderator and the type isn't set as public %>
          <% unless !(@user.admin? || @user.moderator?(bigbluebutton_moderator_roles)) && !bigbluebutton_recording_public_formats.include?(p[:type]) %>
            <% if p[:type] == 'presentation' %>
              <%= link_to p[:url], :'data-toggle' => 'tooltip' , title: p[:type], target: "_blank", class: "mr-4 hover:bg-white hover:text-blue-700" do %>
                <div class="bg-gray-200 p-4 rounded hover:bg-gray-300">
                  <div class= "bg-blue-600 rounded-full" >   
                     <span class="material-icons bg-blue-600 text-white m-2 ml-2.5 md-18"> insert_photo </span>  
                  </div>
                </div>  
              <% end %>
            <% elsif p[:type] == 'statistics' %>
              <%= link_to p[:url], :'data-toggle' => 'tooltip' , title: p[:type], target: "_blank" , class: "mr-4 hover:bg-white hover:text-blue-700 " do %>
              <div class="bg-gray-200 p-4 rounded hover:bg-gray-300">
                <div class= "bg-blue-600 rounded-full">
              <span class="material-icons arrow bg-blue-600 text-white m-2 md-18"> trending_up </span> </div> </div>
              <% end %>
            <% elsif p[:type] == 'video' %>
              <%= link_to p[:url], :'data-toggle' => 'tooltip' , title: p[:type],  target: "_blank", class: "hover:bg-white hover:text-blue-700" do %>
                 <div class="bg-gray-200 p-4 rounded hover:bg-gray-300">
                <div class= "bg-blue-600 rounded-full">
                <span class="material-icons bg-blue-600 text-white m-2 md-18"> play_arrow </span> </div> </div>
              <% end %> 
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </td>
    
  <% if @user.admin? || @user.moderator?(bigbluebutton_moderator_roles) %>
    <td class="p-0 text-left mx-6 mr-2 px-2 my-4">
      <div class="item-action dropdown place-items-center items-center">
        <a href="javascript:void(0)" data-toggle="dropdown" class="bg-white no-underline text-gray-700 hover:text-blue-700 hover:bg-white">
          <i class="material-icons bg-white m-2 hover:text-blue-700">more_vert</i>
        </a>
        <div class="dropdown-content dropdown-menu dropdown-menu-right">
          <% if recording[:published] %>
            <%= link_to recording_unpublish_path(@room, :launch_nonce => @launch_nonce, record_id: recording[:recordID]), method: :post, class: "block px-4 pl-5 py-3  hover:bg-blue-700 hover:text-white font-sans text-xl hover:no-underline" do %>
              <i class="dropdown-icon fas fa-book"></i>&nbsp; <%= t("default.recording.action.unpublish") %>
            <% end %>
          <% else %>
            <%= link_to recording_publish_path(@room, :launch_nonce => @launch_nonce, record_id: recording[:recordID]), method: :post, class: "block px-4 pl-5 py-3  hover:bg-blue-700 hover:text-white font-sans text-xl hover:no-underline" do %>
              <i class="dropdown-icon fas fa-book-open"></i>&nbsp; <%= t("default.recording.action.publish") %>
            <% end %>
          <% end %>
          <%= link_to recording_delete_path(@room, :launch_nonce => @launch_nonce, record_id: recording[:recordID]), method: :post, class: "block px-4 pl-5 py-3 hover:bg-blue-700 hover:text-white font-sans text-xl hover:no-underline" do %>
            <i class="dropdown-icon fas fa-trash-alt"></i>&nbsp; <%= t("default.recording.action.delete") %>
          <% end %>
          <% if recording[:protected] != nil # check if protected field exists %>
            <% if recording[:protected] == "true" %>
                <%= link_to recording_unprotect_path(@room, :launch_nonce => @launch_nonce, record_id: recording[:recordID]), method: :post, class: "block px-4 pl-5 py-3 hover:bg-blue-700 hover:text-white font-sans text-xl hover:no-underline" do %>
                  <i class="dropdown-icon fas fa-unlock-alt"></i>&nbsp; <%= t("default.recording.action.unprotect") %>
                <% end %>
            <% else %>
                <%= link_to recording_protect_path(@room, :launch_nonce => @launch_nonce, record_id: recording[:recordID]), method: :post, class: "block px-4 pl-5 py-3 hover:bg-blue-700 hover:text-white font-sans text-xl hover:no-underline" do %>
                  <i class="dropdown-icon fas fa-lock"></i>&nbsp; <%= t("default.recording.action.protect") %>
                <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </td>
  <% end %>
</tr>

app/views/shared/components/_search_bar.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="row">
  <div class="flex justify-between pt-8 pb-5 items-center">

    <p class="font-sans font-light text-5xl"><%= subtitle %></p>

    <div id="search_bar">
      <div class="input-icon">
        <input type="text" class="form-control btn-pill" placeholder="<%= t('default.recording.search_placeholder') %>">
        <span class="input-icon-addon"></span>
      </div>
    </div>
    
  </div>
<div>